---
version: '3.8'

services:
  postgres:
    image: postgres:16.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    labels:
        - traefik.enable=true
        - traefik.http.routers.postgres.rule=Host(`postgres.musically.localhost`)
        - traefik.http.services.postgres.loadbalancer.server.port=5432
    healthcheck:
        test: ["CMD", "curl", "-f", "http://postgres.musically.localhost"]

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: hydra
    ports:
      - '8081:8080'
    labels:
        - traefik.enable=true
        - traefik.http.routers.adminer.rule=Host(`adminer.musically.localhost`)
        - traefik.http.services.adminer.loadbalancer.server.port=8080
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://adminer.musically.localhost"]

  api:
    build:
        context: .
        dockerfile: docker/api/Dockerfile
        target: dev
    restart: always
    ports:
      - '8080:8080'
    labels:
        - traefik.enable=true
        - traefik.http.routers.api.rule=Host(`api.musically.localhost`)
        - traefik.http.services.api.loadbalancer.server.port=8080
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./target:/app/target
    healthcheck:
      test: ["CMD", "wget", "--spider", "-S", "http://api.musically.localhost"]

  traefik:
    build:
        context: docker/reverse-proxy
        dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
    security_opt:
      - no-new-privileges:true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

volumes:
  db:
